# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_contact', models.CharField(blank=True, help_text="E.164 phone number. WRITE-ONLY — never returned in any API response. Blanked by purge_phi() on resolution. Masked as '+250 78•• •567' if displayed in dashboard.", max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Always set to requested_at + 2 hours. Calculated in save().')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Stamped when status transitions to APPROVED, DENIED, or EXPIRED.', null=True)),
                ('inventory', models.ForeignKey(help_text='The specific inventory record being held. CASCADE means holds are removed if the inventory record is deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='hold_requests', to='inventory.inventory')),
            ],
            options={
                'db_table': 'hold_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_status_expires')],
            },
        ),
    ]
