# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude — fed to Leaflet.js for map pin placement', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude — fed to Leaflet.js for map pin placement', max_digits=9)),
                ('operating_hours', models.CharField(blank=True, help_text="Free-text schedule e.g. 'Mon–Fri 07:00–18:00, Sat 08:00–13:00'", max_length=300)),
                ('emergency_contact', models.CharField(blank=True, help_text="E.164 phone number e.g. '+250788123456'", max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive clinics are hidden from search results but not deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinic',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(help_text='Firebase Authentication UID — the link between this row and Firebase credentials', max_length=128, unique=True)),
                ('username', models.CharField(help_text='Display identifier shown in the dashboard UI', max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Display name for the staff accounts card in Admin Settings', max_length=200)),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('STANDARD_PHARMACIST', 'Standard Pharmacist')], default='STANDARD_PHARMACIST', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive staff cannot authenticate — mirrored to Firebase via firebase_admin.auth.update_user(disabled=True)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(help_text='The clinic this staff member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clinics.clinic')),
            ],
            options={
                'db_table': 'clinic_staff',
                'ordering': ['username'],
            },
        ),
    ]
