# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('ingredient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Standardized INN (International Nonproprietary Name) e.g. 'Paracetamol'", max_length=200, unique=True)),
                ('symptom_category', models.CharField(help_text="Clinical category e.g. 'Analgesic', 'Antibiotic', 'Antimalarial'", max_length=100)),
                ('ems_reference_code', models.CharField(blank=True, help_text='MSF Essential Medicines List reference code', max_length=50)),
            ],
            options={
                'db_table': 'active_ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text="Local brand name e.g. 'Doliprane', 'Panadol'", max_length=200)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('SACHET', 'Sachet'), ('OTHER', 'Other')], max_length=20)),
                ('strength', models.CharField(help_text="e.g. '500mg', '250mg/5ml', 'Standard'", max_length=100)),
                ('ingredient', models.ForeignKey(help_text='The standardized active ingredient this brand is built on. PROTECT prevents deleting an ingredient that has medications registered against it.', on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='medications.activeingredient')),
            ],
            options={
                'db_table': 'medication',
                'ordering': ['brand_name'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'brand_name', 'dosage_form'), name='unique_medication_packaging')],
            },
        ),
    ]
