# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Current physical units in stock. NEVER exposed to client-facing endpoints.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='A StockAlert fires when quantity_on_hand drops to or below this value (FR 4.2)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='OUT_OF_STOCK', editable=False, help_text='Computed automatically on every save — never set directly by serializers', max_length=20)),
                ('is_out_of_stock_override', models.BooleanField(default=False, help_text='Master toggle (FR 3.2). When True, forces status to OUT_OF_STOCK regardless of quantity_on_hand.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text="Auto-stamped on every save — used by the dashboard 'Last updated N min ago' display")),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='clinics.clinic')),
                ('medication', models.ForeignKey(help_text='PROTECT prevents deleting a medication that is actively tracked in inventory', on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='medications.medication')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['medication__brand_name'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], max_length=20)),
                ('quantity_at_trigger', models.PositiveIntegerField(help_text='Snapshot of quantity_on_hand at the exact moment the alert fired')),
                ('is_resolved', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventory')),
                ('staff', models.ForeignKey(blank=True, help_text='The staff member this alert is targeted at. Null = broadcast to all clinic staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='clinics.clinicstaff')),
            ],
            options={
                'db_table': 'stock_alert',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('clinic', 'medication'), name='unique_clinic_medication'),
        ),
    ]
